function [NLine]=Find_Line_Node(KeyPoint,XYData,XYData1) % May-12-2015
%% Purpose: 
%  Find nodes between key-points
%% Input

% XYData =Nodes to define regions
%       =[ Node  X    Y]

%% KeyPoint=[KP1 KP2]=ID of key points (nodes in CYData);
%% XYData1 = data generated by M_Mesh2_A or B

XYK1=XYData(KeyPoint(1),[2 3]);
XYK2=XYData(KeyPoint(2),[2 3]);
XYK=[XYK1-XYK2];
LXY=norm(XYK);
%% check by finding the distance by cross product
IN=XYData1(:,1);

NNode=length(IN);
ILine=[];  % nodes on this line
for i=1:NNode
    In=IN(i);
    XY=XYData1(In,[2 3]);
   
    % Add node if conincident with keypoint
    if( norm(XY-XYK1)==0 || norm(XY-XYK2)==0 ); 
        %disp({'Node ', In ,'is coincident with keypt'})
        ILine=[ILine In];
    else   
        %disp({'Node ', In ,' is not coincident with keypt'})
        V1=[XYK1-XY 0];
        V2=[XYK2-XY 0];
        V12=cross(V1,V2);
        %     V1X=abs(sum(V1.*[XYK 0]))/LXY;
        %     V2X=abs(sum(V2.*[XYK 0]))/LXY;
        V1X=abs(sum(V1.*[XY 0]))/LXY;  % 5-12-15
        V2X=abs(sum(V2.*[XY 0]))/LXY;
        
         VK12 = [XYK1-XYK2 0]/LXY;
         VK21 = [XYK2-XYK1 0]/LXY;
         V1X=abs(dot(V1,VK12));
         V2X=abs(dot(V2,VK21));
         
        %V1X+V2X
        if abs(V12(3))<1e-6 & (V1X+V2X)<=LXY+1e-6; 
            %disp({'Node ' In ' is on the line'})
            ILine=[ILine In]; 
        else
            %disp({'Node ' In ' is NOT on the line'})
        end
    end
end
% disp(['The generated nodes between keypoints[ ',int2str(KeyPoint),' ] are:'])
%     disp(ILine)
NLine=ILine;