function XC=linfib3(T0,T1,phi,a,b,y,x_shift)
%LINFIB
%    YC = LINFIB(T0,T1,A,X)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    05-Oct-2014 22:15:29

T0i= T0;
T0 = T0 * (pi/180.);
T1 = T1 * (pi/180.);

y = y-b/2.;

% special case (T0=T1 && T0i=90)
if( T0 == T1 && T0i == 90)
    y(1:length(y))=x_shift;
    XC=linspace(-b/2,b/2);
    return
end

for i=1:length(y) 
   
    if( T0 == T1 )
        if(T0i == 90)
            XC(i) = 0;
        else
            XC(i) = y(i)*tan(T0);
        end
        XC(i)= XC(i) + b/2.;
    elseif( 0.0 <= y(i) && y(i) <= b/2. )
        XC(i)= ( 0.5*b/(T1-T0)) * ( log(cos(T0)) - log(cos(T0 + 2.*(T1-T0)*y(i)/b) ) );
        XC(i)= XC(i) + b/2.;
    elseif( -b/2.0 <= y(i) && y(i) <= 0.0 )
        XC(i)= ( 0.5*b/(T1-T0)) * (-log(cos(T0)) + log(cos(T0 - 2.*(T1-T0)*y(i)/b) ) );
        XC(i)= XC(i) + b/2.;
    else
        XC(i)=NaN;
    end
    
    XC(i) = XC(i) + x_shift;
    
end