function [F]=thk_legendre(Nmax,xn,yn)
%% Purpose:  Bi-cubic legendre thickness polynomial, numerically, vectorized operation


if(Nmax <= 4)
    % Allocate arrays to save time
    d1=(Nmax+1)^2;
    d2=length(xn);
    F=zeros([d2,d1]);
    
    % Loop over xi,yi
    for i=1:length(xn)
        xi=xn(i); yi=yn(i);
        switch Nmax
            case 1
                [F(i,:)]=thk_legendre_1(xi,yi);
            case 2
                [F(i,:)]=thk_legendre_2(xi,yi);
            case 3
                [F(i,:)]=thk_legendre_3(xi,yi);
            case 4
                [F(i,:)]=thk_legendre_4(xi,yi);
        end
    end
end

function F = thk_legendre_1(x,y)
%THK_LEGENDRE_1
%    F = THK_LEGENDRE_1(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    09-Sep-2015 21:31:01

F = [1.0,y,x,x.*y];

function F = thk_legendre_2(x,y)
%THK_LEGENDRE_2
%    F = THK_LEGENDRE_2(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    09-Sep-2015 21:32:37

t2 = y.^2;
t3 = t2.*(3.0./2.0);
t4 = t3-1.0./2.0;
t5 = x.^2;
t6 = t5.*(3.0./2.0);
t7 = t6-1.0./2.0;
F = [1.0,y,t4,x,x.*y,t4.*x,t7,t7.*y,t4.*t7];

function F = thk_legendre_3(x,y)
%THK_LEGENDRE_3
%    F = THK_LEGENDRE_3(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    09-Sep-2015 21:33:08

t2 = y.^2;
t3 = t2.*(3.0./2.0);
t4 = t3-1.0./2.0;
t5 = t2.*5.0;
t6 = t5-3.0;
t7 = x.^2;
t8 = t7.*(3.0./2.0);
t9 = t8-1.0./2.0;
t10 = t7.*5.0;
t11 = t10-3.0;
F = [1.0,y,t4,t6.*y.*(1.0./2.0),x,x.*y,t4.*x,t6.*x.*y.*(1.0./2.0),t9,t9.*y,t4.*t9,t6.*t9.*y.*(1.0./2.0),t11.*x.*(1.0./2.0),t11.*x.*y.*(1.0./2.0),t4.*t11.*x.*(1.0./2.0),t6.*t11.*x.*y.*(1.0./4.0)];

function F = thk_legendre_4(x,y)
%THK_LEGENDRE_4
%    F = THK_LEGENDRE_4(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    09-Sep-2015 21:33:26

t2 = y.^2;
t3 = t2.*(3.0./2.0);
t4 = t3-1.0./2.0;
t5 = t2.*5.0;
t6 = t5-3.0;
t7 = t2.^2;
t8 = t7.*(3.5e1./8.0);
t13 = t2.*(1.5e1./4.0);
t9 = t8-t13+3.0./8.0;
t10 = x.^2;
t11 = t10.*(3.0./2.0);
t12 = t11-1.0./2.0;
t14 = t10.*5.0;
t15 = t14-3.0;
t16 = t10.^2;
t17 = t16.*(3.5e1./8.0);
t19 = t10.*(1.5e1./4.0);
t18 = t17-t19+3.0./8.0;
F = [1.0,y,t4,t6.*y.*(1.0./2.0),t9,x,x.*y,t4.*x,t6.*x.*y.*(1.0./2.0),t9.*x,t12,t12.*y,t4.*t12,t6.*t12.*y.*(1.0./2.0),t9.*t12,t15.*x.*(1.0./2.0),t15.*x.*y.*(1.0./2.0),t4.*t15.*x.*(1.0./2.0),t6.*t15.*x.*y.*(1.0./4.0),t9.*t15.*x.*(1.0./2.0),t18,t18.*y,t4.*t18,t6.*t18.*y.*(1.0./2.0),t9.*t18];
